
<?php  $this->asDialog = true; ?> 

<?php  $dataProvider = new CArrayDataProvider($rawData=$model->CarriersAir, array()); ?> 

<?php 	
		/*$criteria=new CDbCriteria;
		$criteria->condition = "id_cliente=".$model->id_cliente;								
		$dataProvider = new CActiveDataProvider('Direcciones', array(
			'criteria'=>$criteria,
			'sort'=>array(
			    'defaultOrder'=>'id_direccion ASC',
			),			
		));*/
?> 

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'carriers-air-grid',
	'dataProvider'=>$dataProvider,
	'type' => 'hover striped bordered condensed',
	'selectableRows'=>1,	
	'template' => "{summary}\n{pager}\n{items}\n{summary}\n{pager}",	
	'htmlOptions'=>array('style'=>'cursor: pointer;'),
	'pager'=>array(
		'class' => 'bootstrap.widgets.TbPager',
		'displayFirstAndLast' => true,
		//'class' 		 => 'CLinkPager', 
        'header'         => '',
        'firstPageLabel' => TbHtml::icon(TbHtml::ICON_FAST_BACKWARD),
        'prevPageLabel'  => TbHtml::icon(TbHtml::ICON_STEP_BACKWARD),
        'nextPageLabel'  => TbHtml::icon(TbHtml::ICON_STEP_FORWARD),
        'lastPageLabel'  => TbHtml::icon(TbHtml::ICON_FAST_FORWARD),
    ), 		
	'columns'=>array(
		'CarrierID',
		'Name',
		'CreatedDate',
		'CreatedTime',
		'Expired',
		'CarrierCode',
		/*
		'ver_AWBNumber',
		'hor_AWBNumber',
		'ver_AccountShipperNo',
		'hor_AccountShipperNo',
		'ver_ShipperData',
		'hor_ShipperData',
		'ver_AccountConsignerNo',
		'hor_AccountConsignerNo',
		'ver_ConsignerData',
		'hor_ConsignerData',
		'ver_AgentData',
		'hor_AgentData',
		'ver_AccountInformation',
		'hor_AccountInformation',
		'ver_IATANo',
		'hor_IATANo',
		'ver_AccountAgentNo',
		'hor_AccountAgentNo',
		'ver_AirportDepID',
		'hor_AirportDepID',
		'ver_RequestedRouting',
		'hor_RequestedRouting',
		'ver_AirportToCode1',
		'hor_AirportToCode1',
		'ver_CarrierID',
		'hor_CarrierID',
		'ver_AirportToCode2',
		'hor_AirportToCode2',
		'ver_AirportToCode3',
		'hor_AirportToCode3',
		'ver_CarrierCode2',
		'hor_CarrierCode2',
		'ver_CarrierCode3',
		'hor_CarrierCode3',
		'ver_CurrencyID',
		'hor_CurrencyID',
		'ver_ChargeType',
		'hor_ChargeType',
		'ver_ValChargeType',
		'hor_ValChargeType',
		'ver_OtherChargeType',
		'hor_OtherChargeType',
		'ver_DeclaredValue',
		'hor_DeclaredValue',
		'ver_AduanaValue',
		'hor_AduanaValue',
		'ver_AirportDesID',
		'hor_AirportDesID',
		'ver_FlightDate1',
		'hor_FlightDate1',
		'ver_FlightDate2',
		'hor_FlightDate2',
		'ver_SecuredValue',
		'hor_SecuredValue',
		'ver_HandlingInformation',
		'hor_HandlingInformation',
		'ver_Observations',
		'hor_Observations',
		'ver_NoOfPieces',
		'hor_NoOfPieces',
		'ver_Weights',
		'hor_Weights',
		'ver_WeightsSymbol',
		'hor_WeightsSymbol',
		'ver_Commodities',
		'hor_Commodities',
		'ver_ChargeableWeights',
		'hor_ChargeableWeights',
		'ver_CarrierRates',
		'hor_CarrierRates',
		'ver_CarriersubTot',
		'hor_CarriersubTot',
		'ver_NatureQtyGoods',
		'hor_NatureQtyGoods',
		'ver_TotNoOfPieces',
		'hor_TotNoOfPieces',
		'ver_TotWeight',
		'hor_TotWeight',
		'ver_TotCarrierRate',
		'hor_TotCarrierRate',
		'ver_TotChargeWeightPrepaid',
		'hor_TotChargeWeightPrepaid',
		'ver_TotChargeWeightCollect',
		'hor_TotChargeWeightCollect',
		'ver_TotChargeValuePrepaid',
		'hor_TotChargeValuePrepaid',
		'ver_TotChargeValueCollect',
		'hor_TotChargeValueCollect',
		'ver_TotChargeTaxPrepaid',
		'hor_TotChargeTaxPrepaid',
		'ver_TotChargeTaxCollect',
		'hor_TotChargeTaxCollect',
		'ver_AnotherChargesAgentPrepaid',
		'hor_AnotherChargesAgentPrepaid',
		'ver_AnotherChargesAgentCollect',
		'hor_AnotherChargesAgentCollect',
		'ver_AnotherChargesCarrierPrepaid',
		'hor_AnotherChargesCarrierPrepaid',
		'ver_AnotherChargesCarrierCollect',
		'hor_AnotherChargesCarrierCollect',
		'ver_TotPrepaid',
		'hor_TotPrepaid',
		'ver_TotCollect',
		'hor_TotCollect',
		'ver_TerminalFee',
		'hor_TerminalFee',
		'ver_CustomFee',
		'hor_CustomFee',
		'ver_FuelSurcharge',
		'hor_FuelSurcharge',
		'ver_SecurityFee',
		'hor_SecurityFee',
		'ver_PBA',
		'hor_PBA',
		'ver_TAX',
		'hor_TAX',
		'ver_AdditionalChargeName1',
		'hor_AdditionalChargeName1',
		'ver_AdditionalChargeVal1',
		'hor_AdditionalChargeVal1',
		'ver_AdditionalChargeName2',
		'hor_AdditionalChargeName2',
		'ver_AdditionalChargeVal2',
		'hor_AdditionalChargeVal2',
		'ver_Invoice',
		'hor_Invoice',
		'ver_ExportLic',
		'hor_ExportLic',
		'ver_AgentContactSignature',
		'hor_AgentContactSignature',
		'ver_Instructions',
		'hor_Instructions',
		'ver_AgentSignature',
		'hor_AgentSignature',
		'ver_AWBDate',
		'hor_AWBDate',
		'ver_AirportCode',
		'hor_AirportCode',
		'ver_AdditionalChargeName3',
		'hor_AdditionalChargeName3',
		'ver_AdditionalChargeVal3',
		'hor_AdditionalChargeVal3',
		'ver_AdditionalChargeName4',
		'hor_AdditionalChargeName4',
		'ver_AdditionalChargeVal4',
		'hor_AdditionalChargeVal4',
		'Countries',
		'ver_ChargeType2',
		'hor_ChargeType2',
		'ver_ValChargeType2',
		'hor_ValChargeType2',
		'ver_OtherChargeType2',
		'hor_OtherChargeType2',
		'OtherChargesPrintType',
		'ComisionRate',
		'GroupID',
		'ver_AWBNumber2',
		'hor_AWBNumber2',
		'ver_AWBNumber3',
		'hor_AWBNumber3',
		'ver_id_cliente_order',
		'hor_id_cliente_order',
		'activo',
		'user_insert',
		'date_insert',
		'user_update',
		'date_update',
		'user_auth',
		'date_auth',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',			
			'template'=>'{update}', //{delete}',
			'header' => CHtml::link('<span class="icon-plus icon-white"></span>',Yii::app()->controller->createUrl('/CarriersAir/create'),array('class'=>'btn btn-small btn-primary','onclick'=>'if ("' . $this->asDialog . '") { crud_frame_adjust($(this).attr("href"),"'.Yii::t('app','Create').' '.Yii::t('app','CarriersAir').'",1); return false; }', 'style' => 'display:' . (Yii::app()->session['permisos']['carriersAir']['carriersAir']['create'] == 1 ? 'inline' : 'none'))),			
            'buttons'=>array(            	
                'update'=>
                    array(                    	
                	 	'url'=>'$this->grid->controller->createUrl("/CarriersAir/update", array("id"=>$data->primaryKey))',
						'options'=>array(
    						'onclick'=>'if ("' . $this->asDialog . '") { crud_frame_adjust($(this).attr("href"),"'.Yii::t('app','Update').' '.Yii::t('app','CarriersAir').'",2); return false; }',
	                    ),
	                    'visible' => Yii::app()->session['permisos']['carriersAir']['carriersAir']['update'] == 1 ? 'true' : 'false',
                   	),
                'delete'=>
                    array(                    	
                	 	'url'=>'$this->grid->controller->createUrl("/CarriersAir/delete", array("id"=>$data->primaryKey))',),                   	
            ),				
		),
	),
)); ?>


<?php  $this->asDialog = false; ?> 